"""
Git-integrated build endpoint.
This is an enhanced version of the build endpoint with Git MCP integration.
"""
import os
import sys
from fastapi import APIRouter, HTTPException, Request

# Add shared directory to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '../../../'))

from architect.api.models import BuildRequest, BuildResponse, API_VERSION, API_COMPAT
from architect.router import ArchitectRouter, BuildRequest as ArchBuildRequest
from architect.manifest import ProjectManifest
from architect.paths import workspace_plan_path, root_relative
from architect.api.security import resolve_manifest_path
from architect.logging_utils import log_event
from shared.mcp.git_client import GitMCPClient

router = APIRouter(prefix="/builds", tags=["builds"])


@router.post("/build-with-git", response_model=BuildResponse)
async def execute_build_with_git(request: BuildRequest, http_request: Request) -> BuildResponse:
    """
    Execute a build from an existing plan with Git integration.

    This endpoint:
    1. Loads the existing plan from the workspace
    2. Generates code files based on the plan
    3. Runs tests and attempts self-healing if tests fail
    4. Optionally commits changes to git (if git_options provided)
    5. Returns build results

    Args:
        request: BuildRequest with manifest path and optional git_options

    Returns:
        BuildResponse with build results, artifacts, and git operation results
    """
    try:
        correlation_id = getattr(http_request.state, "correlation_id", None)
        log_event(
            "api.builds_git",
            "build_with_git_started",
            correlation_id=correlation_id,
            manifest_path=request.manifest_path,
            auto_commit=bool(request.git_options and request.git_options.auto_commit),
        )
        safe_manifest_path = resolve_manifest_path(request.manifest_path)

        # Load manifest
        try:
            manifest = ProjectManifest.load(str(safe_manifest_path))
        except Exception as e:
            raise HTTPException(status_code=400, detail=f"Invalid manifest: {str(e)}")

        # Check if plan exists
        plan_path = workspace_plan_path(manifest.id)
        if not plan_path.exists():
            raise HTTPException(
                status_code=404,
                detail=f"Plan not found at {root_relative(plan_path)}. Generate a plan first."
            )

        # Create router and execute build
        arch_router = ArchitectRouter(interactive=False, lazy_memory=True)

        build_req = ArchBuildRequest(
            manifest_path=str(safe_manifest_path),
            request_type="build",
            query="",  # Not needed for build
            correlation_id=correlation_id,
        )

        result = arch_router.process_request(build_req)

        details = result.details or {}
        file_details = details.get("files", {})
        files_built = file_details.get("built", [])
        files_skipped = file_details.get("skipped", [])
        files_failed = file_details.get("failed", [])
        test_results = details.get("tests")

        # Git integration
        git_result = None
        if request.git_options and request.git_options.auto_commit and result.status == "SUCCESS":
            try:
                # Get repo path from manifest
                repo_path = manifest.repo_path or os.getcwd()
                git_client = GitMCPClient(repo_path)

                # Generate commit message if not provided
                commit_message = request.git_options.commit_message
                if not commit_message:
                    # Read plan to generate commit message
                    with open(plan_path, 'r') as f:
                        plan_lines = f.readlines()
                        # Extract first meaningful line as summary
                        summary = "Architect build"
                        for line in plan_lines:
                            line = line.strip()
                            if line and not line.startswith('#'):
                                summary = line[:72]  # Git commit first line limit
                                break

                    commit_message = f"{summary}\n\nGenerated by Architect\n\nCo-Authored-By: Claude Sonnet 4.5 <noreply@anthropic.com>"

                # Determine files to commit
                files_to_commit = request.git_options.files
                if files_to_commit is None and result.artifacts:
                    # Use artifacts as files to commit
                    files_to_commit = result.artifacts

                # Execute git workflow
                git_result = await git_client.auto_commit_and_push(
                    message=commit_message,
                    files=files_to_commit,
                    create_branch=request.git_options.create_branch,
                    push_to_remote=request.git_options.push_to_remote
                )

            except Exception as e:
                # Don't fail the build if git fails, just log it
                git_result = {
                    "success": False,
                    "error": f"Git operation failed: {str(e)}"
                }

        response = BuildResponse(
            status=result.status,
            artifacts=result.artifacts,
            files_built=files_built,
            files_skipped=files_skipped,
            files_failed=files_failed,
            test_results=test_results,
            timing=details.get("timing"),
            build_details=details if details else None,
            summary=result.summary,
            git_result=git_result,
            api_version=API_VERSION,
            api_compat=API_COMPAT,
        )
        log_event(
            "api.builds_git",
            "build_with_git_completed",
            correlation_id=correlation_id,
            project_id=manifest.id,
            status=result.status,
            git_success=git_result.get("success") if isinstance(git_result, dict) else None,
        )
        return response

    except HTTPException:
        raise
    except Exception as e:
        log_event(
            "api.builds_git",
            "build_with_git_failed",
            level="error",
            correlation_id=getattr(http_request.state, "correlation_id", None),
            error=str(e),
        )
        raise HTTPException(status_code=500, detail=f"Failed to execute build: {str(e)}")
